pipeline{
    agent any 
    stages{
        stage('Source_Code_Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Monish-Samuel/powershell_testing.git']]])
            }
        }
        stage('Build Number Check'){
		steps{	
			powershell '$BUILD_NUMBER= $env:BUILD_NUMBER'
			powershell 'Write-Host $BUILD_NUMBER'
		}	
	}    
    }
}
