pipeline{
    agent any 
    stages{
        stage('Source_Code_Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Monish-Samuel/powershell_testing.git']]])
            }
        }
        stage('Build Number Check'){
		steps{	
			echo "The build number is ${env.BUILD_NUMBER}"
		}	
	}    
    }
}
